Updated project root files for packagist.
SU-SWS/trustee_profile pull request #1
Opened 2021-12-16 21:02 UTC by mdyoung3

# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Urgency
- How urgent is this? (Normal, High)

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2022-01-07 20:04 UTC, joegl requested changes
@mdyoung3 This is lookin good just a few small changes/suggestions.

2022-01-07 20:04 UTC, joegl commented on modules/trustee_profile_helper/ trustee_profile_helper.module
> + * Contains caw_profile_helper.module.
```suggestion
 * Contains trustee_profile_helper.module.
```

@mdyoung3 It also looks like there's possibly a space at the beginning of file name? 

`trustee_profile_helper/ trustee_profile_helper.module`

2022-01-07 20:04 UTC, joegl commented on modules/trustee_profile_helper/trustee_profile_helper.info.yml
> +package: 'trustee'
```suggestion
package: 'trustee'

```

2022-01-07 20:04 UTC, joegl commented on trustee_profile.info.yml
> +description: 'Jumpstart Website Profile for the Board of Trustee website'
```suggestion
description: 'Jumpstart Website Profile for Board of Trustees Intranet sites'
```

2022-01-07 20:05 UTC, joegl commented on modules/trustee_profile_helper/trustee_profile_helper.info.yml
> +description: 'Add on module and functionality for CAW.'
```suggestion
description: 'Add on module and functionality for Board of Trustees.'
```

2022-01-07 21:00 UTC, mdyoung3 commented on modules/trustee_profile_helper/ trustee_profile_helper.module
> + * Contains caw_profile_helper.module.
Fixed

2022-01-07 23:12 UTC, joegl requested changes
Looks great! Looks like this filename still has a space in it though (unless that's just me?): `modules/trustee_profile_helper/ trustee_profile_helper.module`

![trustee-space](https://user-images.githubusercontent.com/6943710/148618864-5a8667ef-5f05-4b00-a2f6-062c3a7b81b7.png)

2022-01-07 23:19 UTC, joegl commented on modules/trustee_profile_helper/trustee_profile_helper.module
> + * Contains caw_profile_helper.module.
```suggestion
 * Contains trustee_profile_helper.module.
```

2022-01-07 23:32 UTC, joegl approved these changes
This LGTM but I'd wait for Mike to peek at it before merging.

2022-01-07 23:41 UTC, pookmish requested changes

2022-01-07 23:41 UTC, pookmish commented on config/sync/core.extension.yml
> -  stanford_profile_helper: 10
You'll want to keep using the `stanford_profile_helper`.

2022-01-07 23:41 UTC, pookmish commented on trustee_profile.install
> +function trustee_profile_update_8002() {
You can remove the function

2022-01-07 23:41 UTC, pookmish commented on trustee_profile.post_update.php
> +  \Drupal::service('module_installer')->uninstall(['search']);
You can remove these since this profile is new.

2022-01-07 23:43 UTC, pookmish commented
Please set up codeclimate as well

2022-01-11 23:35 UTC, mdyoung3 commented
@pookmish I set up Codeclimate.  It appears to fail. I compared the config files to other projects and it looks simpatico. I suspect we need to complete setup before the test will pass. Is that correct?

2022-01-12 17:50 UTC, pookmish commented
> @pookmish I set up Codeclimate. It appears to fail. I compared the config files to other projects and it looks simpatico. I suspect we need to complete setup before the test will pass. Is that correct, or should I troubleshoot this?

Yeah I see codeclimate is having some issues lately.

Go ahead and fix up the acceptance tests and then this can be merged. But please work on the codeclimate soon.

2022-01-12 19:23 UTC, mdyoung3 commented
@pookmish Wouldn't the tests be the same as ace-gyphon since we haven't made any changes to it?

2022-01-12 19:41 UTC, pookmish commented
> @pookmish Wouldn't the tests--acceptance or otherwise--be the same as ace-gyphon since we haven't made any changes to it? Or is that it, there things specific to ace-gryphon?

This is the profile. `ace-gryphon` is the stack. You've changed configs and namespaces in this profile. the tests themselves aren't even running at this time. The profile won't even install.

2022-01-12 20:17 UTC, mdyoung3 commented
I'm more talking about the acceptance testing. For example, the HomePageCest tests for the home page route, looks for text and logs in with admin. 

```  public function testHomepage(AcceptanceTester $I) {
    $I->amOnPage('/');
    $I->canSee('Stanford');
    $I->seeCurrentUrlEquals('/');
    $I->canSee('Welcome to your site!', 'h2');
    $I->logInWithRole('administrator');
    $I->amOnPage('/admin/structure');
    $I->canSeeResponseCodeIs(200);
  }
```

So when you say "fix up the acceptance tests" what do you mean?

2022-01-12 21:05 UTC, pookmish commented
> So when you say "fix up the acceptance tests" what do you mean?

https://app.circleci.com/pipelines/github/SU-SWS/trustee_profile/20/workflows/c9bc4ccf-01e7-4edc-8fb7-011653597d32/jobs/40

2022-01-13 20:14 UTC, mdyoung3 commented
Okay I think I know what you mean now, Mike. I'm seeing the same issue on my local as testing. And `blt doctor` is saying there's config issues.

2022-01-13 21:15 UTC, pookmish commented
> Okay I think I know what you mean now, Mike. I'm seeing the same issue on my local as testing. And `blt doctor` is saying there's config issues.

Yes, there's config issues. See the screenshot from the tests:
![image](https://user-images.githubusercontent.com/7185045/149410261-90cfce98-39d5-4fc6-9f16-902a99f3b8e9.png)

2022-01-19 17:54 UTC, mdyoung3 commented
Hey @pookmish 

The test are running now, but failing at multiple points. One question I have is, is it possible that anything on the stack side of things is causing this atm? If I remember correctly (and that's a big if), this maybe runs in a vanilla Drupal site.

2022-01-19 18:33 UTC, pookmish commented
@mdyoung3, The problem was the CircleCi environment was missing the `STANFORD_ENCRYPT` variable. It just needed to be a 32 character random string. Once I added that and re-ran the tests, everything passed. This is g2g.

2022-01-19 18:34 UTC, merged

2022-01-19 18:40 UTC, mdyoung3 commented
Cool. Thanks!